### PR TITLE
transform: fixed type conversions

### LINKED ISSUE #52: Ensure that type casts don't lose information
### What
Some type casts in the transform package may be invalid. Casting from uint32 to int32 could result in a loss of information, since uint32s have a higher maximum value. Similarly, casting from int64 to int32 could result in a loss of information. We need to ensure these casts do not happen, likely by changing the type of the field in the output struct to ensure it can hold all the information.
### Why
Losing data in type casts makes the ETL transform functions unreliable. We want to have an accurate and complete picture of the data.

### PR DESCRIPTION
**Pull request by Isaiah-Turner**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).
</details>

### What
This PR makes fixes to type conversions that could have resulted in a loss of data. Now all type conversions should be from xdr wrapper types to their corresponding built-in go types. Closes #52.

### Why
We don't want the transform functions to lose data. The ETL output should be correct and consistent with the ingestion system data.

### CODE REVIEW

File: internal/transform/account.go [hunk 1]
```diff
@@ -45,9 +45,6 @@ func TransformAccount(ledgerEntry xdr.LedgerEntry) (AccountOutput, error) {
 	}
 
 	outputNumSubentries := uint32(accountEntry.NumSubEntries)
-	if outputNumSubentries < 0 {
```
Comment (debnil) [inline internal/transform/account.go:48]: Good catch with the uints :)

File: internal/transform/ledger.go [hunk 2]
```diff
@@ -53,27 +50,16 @@ func TransformLedger(inputLedgerMeta xdr.LedgerCloseMeta) (LedgerOutput, error)
...
-		return LedgerOutput{}, fmt.Errorf("The base reserve (%d) is negative for ledger %d", outputBaseReserve, outputSequence)
-	}
+	outputBaseReserve := uint32(ledgerHeader.BaseReserve)
 
-	outputMaxTxSetSize := int32(ledgerHeader.MaxTxSetSize)
-	if outputMaxTxSetSize < 0 {
-		return LedgerOutput{}, fmt.Errorf("The max transaction set size (%d) is negative for ledger %d", outputMaxTxSetSize, outputSequence)
-	} else if outputMaxTxSetSize < outputTransactionCount {
+	outputMaxTxSetSize := uint32(ledgerHeader.MaxTxSetSize)
+	if int64(outputMaxTxSetSize) < int64(outputTransactionCount) {
```
Comment (debnil) [inline internal/transform/ledger.go:58]: Why the cast here for value comparison?

Comment (Isaiah-Turner) [reply internal/transform/ledger.go:58]: outputMaxTxSetSize is a uint32 and outputTransactionCount is an int32. By casting to an int64, both of their respective data ranges are captured and they can be compared safely.
